Fix Git prepare-commit-msg
Don't output/parse the commit message file unless it is a new commit

diff --git a/config/git/.git-template/hooks/pre-push b/config/git/.git-template/hooks/pre-push
--- a/config/git/.git-template/hooks/pre-push
+++ b/config/git/.git-template/hooks/pre-push
@@ -12,9 +12,9 @@ ARGS+=(--hook-dir "$HERE" -- "$@")
 
 if [ -x "$INSTALL_PYTHON" ]; then
     exec "$INSTALL_PYTHON" -mpre_commit "${ARGS[@]}"
-elif command -v pre-commit > /dev/null; then
+elif command -v pre-commit >/dev/null; then
     exec pre-commit "${ARGS[@]}"
 else
-    echo "\`pre-commit\` not found.  Did you forget to activate your virtualenv?" 1>&2
+    echo '`pre-commit` not found.  Did you forget to activate your virtualenv?' 1>&2
     exit 1
 fi
